### ISSUE TITLE
Fails on Ghidra 9.1.2

### ISSUE THREAD

**Issue by n1zzo** [elliiot/ghidra_darknight#10]
The program fails on the latest Ghidra 9.1.2.

```
Traceback (most recent call last):
  File "./set_colors.py", line 71, in <module>
    copyfile("black_dragon.png", dragon_path)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.ghidra/.ghidra-9.0/tools/black_dragon.png'
```

**Comment by sw33n3y** [comment]
Have you tried using a random (probably 256x256) PNG image and titling it **black_dragon.png** and placing it at that location specified? That's all the error is you are receiving.

I have a feeling it might still fail as for me on my windows machine this file:
**.ghidra/.ghidra_9.1.2_PUBLIC/tools/_code_browser.tcd** seems to have changed dramatically between ghidra versions 9.1.1 and 9.1.2.

I am also using an altered version of this theme found: https://digmi.org/2019/03/26/ghidracula/


EDIT: 8:46 5/27/2020

1. open **set_colors.py** script
2. GOTO line 69 (nice)
3. Get rid of: **expanduser("~") + stuff.**
4. Replace it with the location of your "_code_browser.tcd" file is.

For me I had cygwin installed which is kinda linux filenames styles on windows so it created a weird and incorrect path.

The Directory being created was

**C:\\Users\\[USERNAME]\\Cygwin/.ghidra/.ghidra-9.0/tools/black_dragon.png'**

But the actually directory was:

**C:\Users\[USERNAME]\.ghidra\.ghidra_1.9.2-PUBLIC\tools\black_dragon.png**


I hope this helps. Goodday.
