### ISSUE TITLE
Doesn't work in MacOS

### ISSUE THREAD

**Issue by eduarcor** [elliiot/ghidra_darknight#6]
In MacOS, I am not able to make it work.
When applied it says:
Exited with error.  Run in foreground (fg) mode for more details. (1)

**Comment by racerxdl** [comment]
Same for linux. Running with foreground mode gives me this:

```
./support/launch.sh fg Ghidra "${MAXMEM}" "" ghidra.GhidraRun "$@"
OpenJDK 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "ghidra.GhidraClassLoader"). To use archived non-system classes, this property must be not be set
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)
Error: Uncaught Exception! 
NoClassDefFoundError - utility/applicaiton/ApplicationLayout
java.lang.NoClassDefFoundError: utility/applicaiton/ApplicationLayout
	at ghidra.StatusReportingTaskMonitor.setMessage(GhidraRun.java:254)
	at ghidra.framework.Application.initializeLogging(Application.java:144)
	at ghidra.framework.Application.initialize(Application.java:94)
	at ghidra.framework.Application.initializeApplication(Application.java:114)
	at ghidra.GhidraRun.lambda$launch$1(GhidraRun.java:78)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: utility.applicaiton.ApplicationLayout
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 6 more
```
